version: '3'
services:
  app:
    build: .docker
    ports:
      - 8089:80
    volumes:
      - ./webSite:/var/www/html
      - .docker/nginx.conf:/etc/nginx/sites-enabled/site:ro
    environment:
      TZ: Europe/Istanbul

  redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      TZ: Europe/Istanbul

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fatih
      MYSQL_USER: fatih
      MYSQL_PASSWORD: XjQ6lPre5q
      TZ: Europe/Istanbul

volumes:
  mysql: